### ISSUE TITLE
Missing Launcher

### ISSUE THREAD

**Issue by Melquiii** [YouFool/go-file-downloader#1] opened 2021-07-25 01:22 UTC
Hi! I downloaded the zip file and I can't seem to find the launcher for this tool. I really like the concept and would like to test it out and how it works. Thank you!

**Comment by YouFool** [comment] 2021-07-25 03:14
Hey @Melquiii, thanks for filling the very first issue!

Yeah, when I built this tool I forgot to provide instructions on how to use it. So, here you go:

1. You will need [Go 1.14 or higher](https://golang.org/dl/) installed to compile the source code
2. As you've downloaded the source code as a .zip file, you'll need to unzip it and create a folder called `output` inside it
3. With Go installed and the output folder created, let's compile the source code inside the unzipped directory
3.1 Open the terminal and execute `cd path/to/unzipped-dir && go build`. In example: `cd C:\Users\myUser\Downloads\go-file-downloader && go build` This command will generate an executable file _(.exe)_ inside the folder.
4. Once the program is compiled successfully, you just need to provide a file called `input.txt` with the URLs to download (each link must be separated from the other by a line feed) and execute the _.exe_ file. 
5. That's it! You're ready to go!

Program output will be shown as below:
![image](https://user-images.githubusercontent.com/37518972/126886083-709f4488-abdc-411a-bb3e-260158db321b.png)

At the end of execution, the downloader will create a cache file (__downloadedCache_) with all downloaded URLs. If some error occurred while downloading file(s) you can just run it again and download the failed ones.

I'll also update the README of this repository with the instructions here. Feel free to contribute to this repo with feature requests, issues, or pull requests.

Again, thanks for filling the issue, I hope the downloader fills your needs! Let me know if it works out for you!

**Comment by Melquiii** [comment] 2021-07-27 12:55
Thank you very much for the response! It's a pleasure to have you send me
the entire steps. I appreciate it very much!

**Comment by YouFool** [comment] 2021-07-29 03:12
I also appreciate opening the issue! Let me know if you were able to compile the project and download some files, I would love to hear some feedback on the downloader performance!

**Comment by YouFool** [comment] 2021-08-24 03:34
Closing issue since the problem is solved.

**Closed as completed by YouFool** 2021-08-24 03:34 UTC
Labels: documentation
